theme: jekyll-theme-architect

title: Vibotian
description: [this is my personal blog, which i express my opinion and show my work]
show_downloads: ["true"]
google_analytics: [Your Google Analytics tracking ID]

github:
  zip_url: https://github.com/Kivo0/background_subtraction/archive/master.zip
  another_url: www.google.com
